services:
  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - hexgridgame-redis-data:/hex-grid-data

  # server:
  #   container_name: hex-grid-game
  #   depends_on:
  #     - redis
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: backend
  #   environment:
  #     - REDIS_ADDRESS=redis:6379
  #     - REDIS_PUBSUB_CHANNEL=channel1
  #   ports:
  #     - 80:80
  #     - 5001:5001
  #     - 2345:2345
  #   networks:
  #     - mynetwork

volumes:
  hexgridgame-redis-data:

networks:
  mynetwork: